### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by LeThiHyVong** [kobalicek/reloaded-cpp#4]
Issue Type: <b>Bug</b>

I am working on [JSMin](https://github.com/douglascrockford/JSMin)
The Reloaded C++ make the syntax highlighting wrong, after disabling Reloaded C++ go well.
![screenshot_2018-07-28_09-43-13](https://user-images.githubusercontent.com/19317679/43352249-f5691614-924a-11e8-97f2-0f736bf49d48.png)
I think there is bug in regex recognized string. 
Thanks.

Extension version: 0.1.6
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.5-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 1899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.16GB (0.14GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by LeThiHyVong** [comment]
Ok, I found out a walkathrough
Add `(?:[^'])` before string begin and after end patterns.

**Comment by kobalicek** [comment]
Should be fixed by f13ddbb24f1775e9cd92c5b415a1a618a4eb5a25
