### ISSUE TITLE
C++14 digits separators incorrectly highlighted in integer literals.

### ISSUE THREAD

**Issue by daphnediane** [kobalicek/reloaded-cpp#6]
Literals like 0xFFFF'FFFFU are highlighted as if the C++14 digit separator opens a quoted string until the end of the file, or next uneven digit separator. These used to display correctly.

See [n3781 Single-Quotation-Mark as a Digit Separator](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3781.pdf)

**Comment by kobalicek** [comment]
Thanks, should be fixed by https://github.com/kobalicek/reloaded-cpp/commit/6ebc3932eeaf8fbc0b2946d9ba99c1d01326e7b9

**Comment by daphnediane** [comment]
Thanks
